### ISSUE TITLE
开发模式忽略了test文件夹

### ISSUE THREAD

**Issue by itbeihe** [jdf2e/jdf#8]
在 /jdfx/lib/VFS/fileType.js文件24行，忽略了 test 文件和文件夹。
某些情况可能还是想给文件夹起名test的，想问下开发开发模式忽略test文件夹的原因？

**Comment by chenxiaochun** [comment]
默认情况下，我们确实是忽略了`test`文件夹。
想要输出的话可以参考文档：https://github.com/jdf2e/jdf/blob/master/doc/a_tool_config.md
其中有一个`outputCustom`参数，配置一下即可。
